/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cbs.gui;

import java.sql.SQLException;
import javax.swing.JOptionPane;
import cbs.auth.Authentication;

/**
 *
 * @author Ahmed
 */

public class LoginFrame extends javax.swing.JFrame {

    /**
     * Creates new form LoginFrame
     */
    public LoginFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainLoginPanel = new javax.swing.JPanel();
        Right = new javax.swing.JPanel();
        LOGO_B = new javax.swing.JLabel();
        LOGO_S = new javax.swing.JLabel();
        LOGO_BANKSYSTEM = new javax.swing.JLabel();
        Left = new javax.swing.JPanel();
        LoginLabel = new javax.swing.JLabel();
        UserNameLabel = new javax.swing.JLabel();
        PasswordLabel = new javax.swing.JLabel();
        PasswordField = new javax.swing.JPasswordField();
        SubmitButton = new javax.swing.JButton();
        UserNameTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BS | LOGIN");
        setMaximumSize(new java.awt.Dimension(800, 500));
        setMinimumSize(new java.awt.Dimension(800, 500));
        setPreferredSize(new java.awt.Dimension(800, 500));

        MainLoginPanel.setBackground(new java.awt.Color(204, 204, 204));
        MainLoginPanel.setPreferredSize(new java.awt.Dimension(800, 500));
        MainLoginPanel.setLayout(null);

        Right.setBackground(new java.awt.Color(55, 151, 119));
        Right.setPreferredSize(new java.awt.Dimension(400, 500));
        Right.setLayout(null);

        LOGO_B.setFont(new java.awt.Font("Okruglizm", 0, 96)); // NOI18N
        LOGO_B.setForeground(new java.awt.Color(1, 240, 164));
        LOGO_B.setText("B");
        Right.add(LOGO_B);
        LOGO_B.setBounds(120, 150, 71, 103);

        LOGO_S.setFont(new java.awt.Font("Okruglizm", 0, 96)); // NOI18N
        LOGO_S.setForeground(new java.awt.Color(34, 40, 49));
        LOGO_S.setText("S");
        Right.add(LOGO_S);
        LOGO_S.setBounds(190, 150, 73, 103);

        LOGO_BANKSYSTEM.setFont(new java.awt.Font("Okruglizm", 0, 36)); // NOI18N
        LOGO_BANKSYSTEM.setForeground(new java.awt.Color(255, 255, 255));
        LOGO_BANKSYSTEM.setText("Bank System");
        Right.add(LOGO_BANKSYSTEM);
        LOGO_BANKSYSTEM.setBounds(60, 250, 290, 40);

        MainLoginPanel.add(Right);
        Right.setBounds(0, 0, 400, 500);

        Left.setBackground(new java.awt.Color(245, 247, 248));
        Left.setForeground(new java.awt.Color(255, 255, 255));
        Left.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        Left.setPreferredSize(new java.awt.Dimension(400, 500));

        LoginLabel.setFont(new java.awt.Font("Montserrat ExtraBold", 0, 32)); // NOI18N
        LoginLabel.setForeground(new java.awt.Color(69, 71, 75));
        LoginLabel.setText("LOGIN");

        UserNameLabel.setFont(new java.awt.Font("Montserrat Medium", 0, 20)); // NOI18N
        UserNameLabel.setForeground(new java.awt.Color(69, 71, 75));
        UserNameLabel.setText("User name:");

        PasswordLabel.setFont(new java.awt.Font("Montserrat Medium", 0, 20)); // NOI18N
        PasswordLabel.setForeground(new java.awt.Color(69, 71, 75));
        PasswordLabel.setText("Password:");

        PasswordField.setBackground(new java.awt.Color(255, 255, 255));
        PasswordField.setForeground(new java.awt.Color(69, 71, 75));
        PasswordField.setText("mohamed");
        PasswordField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 12, 1, 1));
        PasswordField.setMargin(new java.awt.Insets(5, 6, 2, 6));
        PasswordField.setPreferredSize(new java.awt.Dimension(103, 26));

        SubmitButton.setBackground(new java.awt.Color(244, 206, 20));
        SubmitButton.setFont(new java.awt.Font("Montserrat Medium", 0, 20)); // NOI18N
        SubmitButton.setForeground(new java.awt.Color(69, 71, 75));
        SubmitButton.setText("Login");
        SubmitButton.setBorder(null);
        SubmitButton.setPreferredSize(new java.awt.Dimension(170, 38));
        SubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                    SubmitButtonActionPerformed(evt);
            }
        });

        UserNameTextField.setBackground(new java.awt.Color(255, 255, 255));
        UserNameTextField.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        UserNameTextField.setForeground(new java.awt.Color(69, 71, 75));
        UserNameTextField.setText("mohamed");
        UserNameTextField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 12, 1, 1));

        javax.swing.GroupLayout LeftLayout = new javax.swing.GroupLayout(Left);
        Left.setLayout(LeftLayout);
        LeftLayout.setHorizontalGroup(
            LeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LeftLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(LeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PasswordField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(LeftLayout.createSequentialGroup()
                        .addGroup(LeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LoginLabel)
                            .addComponent(UserNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(UserNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PasswordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SubmitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(61, 61, 61))
        );
        LeftLayout.setVerticalGroup(
            LeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LeftLayout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(LoginLabel)
                .addGap(18, 18, 18)
                .addComponent(UserNameLabel)
                .addGap(5, 5, 5)
                .addComponent(UserNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(PasswordLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(SubmitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(124, 124, 124))
        );

        MainLoginPanel.add(Left);
        Left.setBounds(400, 0, 400, 500);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(MainLoginPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(MainLoginPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        MainLoginPanel.getAccessibleContext().setAccessibleName("");

        getAccessibleContext().setAccessibleName("LOGIN");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitButtonActionPerformed
        // TODO add your handling code here:
        char[] pf = PasswordField.getPassword();
        String value = new String(pf);
        
        try {
            if (Authentication.check_auth(UserNameTextField.getText(), value)) {
                JOptionPane.showMessageDialog(this, "Welcome back Mr." + UserNameTextField.getText());
                dispose();
                MainWindow mainWindow = new MainWindow();
                mainWindow.setVisible(true);
                mainWindow.pack();
                mainWindow.setLocationRelativeTo(null);
            }
            else {
                JOptionPane.showMessageDialog(this, "Username or Passowrd is invalid!", "Try agin!", JOptionPane.ERROR_MESSAGE);
            }
        }
        catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "User name or Passowrd is invalid!", "Try again!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_SubmitButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LOGO_B;
    private javax.swing.JLabel LOGO_BANKSYSTEM;
    private javax.swing.JLabel LOGO_S;
    private javax.swing.JPanel Left;
    private javax.swing.JLabel LoginLabel;
    private javax.swing.JPanel MainLoginPanel;
    private javax.swing.JPasswordField PasswordField;
    private javax.swing.JLabel PasswordLabel;
    private javax.swing.JPanel Right;
    private javax.swing.JButton SubmitButton;
    private javax.swing.JLabel UserNameLabel;
    private javax.swing.JTextField UserNameTextField;
    // End of variables declaration//GEN-END:variables
}
